// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Directives = 1,
  Commands = 2,
  Extensions = 3,
  Reporters = 4,
  TurtleVars = 5,
  PatchVars = 6,
  LinkVars = 7,
  Constants = 8,
  Unsupported = 9,
  LineComment = 10,
  Program = 11,
  Numeric = 12,
  String = 13
